# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0002_auto_20181025_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='number',
        ),
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(default=0),
        ),
    ]
