# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0004_auto_20181025_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='info',
            field=models.TextField(max_length=100),
        ),
    ]
